# Form implementation generated from reading ui file 'inna_gui.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDateTime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 392)
        MainWindow.setMinimumSize(QtCore.QSize(70, 20))
        MainWindow.setStyleSheet("")
        MainWindow.setWindowIcon(QtGui.QIcon("img/window_icon.svg"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 80, 361, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.enter_name = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.enter_name.setContentsMargins(5, 5, 5, 5)
        self.enter_name.setObjectName("enter_name")
        self.label_enter_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_enter_name.setObjectName("label_enter_name")
        self.enter_name.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_enter_name)
        self.lineEdit_enter_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_enter_name.setObjectName("lineEdit_enter_name")
        self.enter_name.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_enter_name)
        self.button_confirm_name = QtWidgets.QPushButton(self.centralwidget)
        self.button_confirm_name.setGeometry(QtCore.QRect(266, 110, 101, 25))  # 1 - х, 2 - у, 3 - ширина, 4 - высота
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_confirm_name.sizePolicy().hasHeightForWidth())
        self.button_confirm_name.setSizePolicy(sizePolicy)
        self.button_confirm_name.setObjectName("button_conform_name")
        self.pushButton_open_scheme = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_scheme.setGeometry(QtCore.QRect(10, 300, 85, 25))  # 1 - х, 2 - у, 3 - ширина, 4 - высота
        self.pushButton_open_scheme.setObjectName("pushButton_open_scheme")
        self.pushButton_open_cooling = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_cooling.setGeometry(QtCore.QRect(100, 300, 130, 25))  # 1- х, 2 - у, 3 - ширина, 4 - высота
        self.pushButton_open_cooling.setObjectName("pushButton_open_cooling")
        self.pushButton_open_control = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_control.setGeometry(QtCore.QRect(235, 300, 75, 25))  # 1 - х, 2 - у, 3 - ширина, 4 - высота
        self.pushButton_open_control.setObjectName("pushButton_open_control")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(714, 360, 91, 25))  # 1 - х, 2 - у, 3 - ширина, 4 - высота
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 291, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.operator_works = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.operator_works.setContentsMargins(0, 0, 0, 0)
        self.operator_works.setObjectName("operator_works")
        self.label_operator_works = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_operator_works.setObjectName("label_operator_works")
        self.operator_works.addWidget(self.label_operator_works)
        self.label_work_name_operator = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_work_name_operator.setObjectName("label_work_name_operator")
        self.operator_works.addWidget(self.label_work_name_operator)
        self.gridFrame_diagnostics = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame_diagnostics.setGeometry(QtCore.QRect(460, 20, 341, 331))
        self.gridFrame_diagnostics.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gridFrame_diagnostics.setObjectName("gridFrame_diagnostics")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame_diagnostics)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_diagnostics = QtWidgets.QLabel(self.gridFrame_diagnostics)
        self.label_diagnostics.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_diagnostics.setObjectName("label_diagnostics")
        self.gridLayout.addWidget(self.label_diagnostics, 0, 0, 1, 1)
        self.label_ready = QtWidgets.QLabel(self.gridFrame_diagnostics)
        self.label_ready.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_ready.setObjectName("label_ready")
        self.gridLayout.addWidget(self.label_ready, 3, 0, 1, 1)
        self.gridFrame_devices = QtWidgets.QFrame(self.gridFrame_diagnostics)
        self.gridFrame_devices.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gridFrame_devices.setObjectName("gridFrame_devices")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_devices)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_plc_green_red = QtWidgets.QLabel(self.gridFrame_devices)
        self.label_plc_green_red.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_plc_green_red.setObjectName("label_plc_green_red")
        self.gridLayout_2.addWidget(self.label_plc_green_red, 1, 0, 1, 1)
        self.label_pressure_4_green_red = QtWidgets.QLabel(self.gridFrame_devices)
        self.label_pressure_4_green_red.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_pressure_4_green_red.setObjectName("label_pressure_4_green_red")
        self.gridLayout_2.addWidget(self.label_pressure_4_green_red, 3, 1, 1, 1)
        self.label_pressure_2_green_red = QtWidgets.QLabel(self.gridFrame_devices)
        self.label_pressure_2_green_red.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_pressure_2_green_red.setObjectName("label_pressure_2_green_red")
        self.gridLayout_2.addWidget(self.label_pressure_2_green_red, 2, 1, 1, 1)
        self.label_temp_green_red = QtWidgets.QLabel(self.gridFrame_devices)
        self.label_temp_green_red.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_temp_green_red.setObjectName("label_temp_green_red")
        self.gridLayout_2.addWidget(self.label_temp_green_red, 1, 1, 1, 1)
        self.label_pressure_3_green_red = QtWidgets.QLabel(self.gridFrame_devices)
        self.label_pressure_3_green_red.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_pressure_3_green_red.setObjectName("label_pressure_3_green_red")
        self.gridLayout_2.addWidget(self.label_pressure_3_green_red, 3, 0, 1, 1)
        self.label_pressure_1_green_red = QtWidgets.QLabel(self.gridFrame_devices)
        self.label_pressure_1_green_red.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_pressure_1_green_red.setObjectName("label_pressure_1_green_red")
        self.gridLayout_2.addWidget(self.label_pressure_1_green_red, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.gridFrame_devices, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        #self.lineEdit_enter_name.textEdited['QString'].connect(self.label_work_name_operator.setText)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_confirm_name, self.pushButton_open_cooling)
        MainWindow.setTabOrder(self.pushButton_open_cooling, self.pushButton_open_control)
        MainWindow.setTabOrder(self.pushButton_open_control, self.lineEdit_enter_name)
        MainWindow.setTabOrder(self.lineEdit_enter_name, self.pushButton_close)
        MainWindow.setTabOrder(self.pushButton_close, self.pushButton_open_scheme)

        # button
        self.button_confirm_name.clicked.connect(self.confirm_name)

    # button logik
    def confirm_name(self):
        a = self.lineEdit_enter_name.text()
        self.label_work_name_operator.setText("{}".format(a))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INNA"))
        self.label_enter_name.setText(_translate("MainWindow", "Введите имя оператора"))
        self.button_confirm_name.setText(_translate("MainWindow", "Подтвердить"))
        self.pushButton_open_scheme.setText(_translate("MainWindow", "Мнемосхема"))
        self.pushButton_open_cooling.setText(_translate("MainWindow", "Система охлождения"))
        self.pushButton_open_control.setText(_translate("MainWindow", "Управление"))
        self.pushButton_close.setText(_translate("MainWindow", "Выход"))
        self.label_operator_works.setText(_translate("MainWindow", "Работает оператор:"))
        self.label_work_name_operator.setText(_translate("MainWindow", "TextLabel"))
        self.label_diagnostics.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" "
                                                                "font-weight:600;\">Диагностика</span></p></body></html>"))
        self.label_ready.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" "
                                                          "font-weight:600;\">Готовность(зелкрас)</span></p></body></html>"))
        self.label_plc_green_red.setText(_translate("MainWindow", "Связь с ПЛК(зелкрас)"))
        self.label_pressure_4_green_red.setText(_translate("MainWindow", "Давление 4 (зелкрас)"))
        self.label_pressure_2_green_red.setText(_translate("MainWindow", "Давление 2 (зелкрас)"))
        self.label_temp_green_red.setText(_translate("MainWindow", "Температура(данные)"))
        self.label_pressure_3_green_red.setText(_translate("MainWindow", "Давление 3 (зелкрас)"))
        self.label_pressure_1_green_red.setText(_translate("MainWindow", "Давление 1 (зелкрас)"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
