# Form implementation generated from reading ui file 'cooling.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets, QtGui
from PyQt6.QtCore import QThread
from PyQt6.QtWidgets import QMessageBox
import sys

from cooling.modbusRTU import *
import time


class Thread(QThread):
    def __init__(self, label_temp, label_speed):
        super().__init__()
        self.label_temp = label_temp
        self.label_speed = label_speed

    def run(self):
        while True:
            self.label_temp.setText("{}".format(run_sync_client_temp()))
            self.label_speed.setText("{}".format(run_sync_client_flow()))
            time.sleep(5)


class Ui_cooling(object):
    def setupUi(self, cooling):
        cooling.setObjectName("cooling")
        cooling.resize(439, 339)
        # icon = QtGui.QIcon('../img/cooling_icon.svg')
        # icon.addPixmap(QtGui.QPixmap("../img/cooling_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # cooling.setWindowIcon(icon)
        cooling.setWindowTitle("Система охлаждения")
        self.button_on_drive = QtWidgets.QPushButton(parent=cooling)
        self.button_on_drive.setGeometry(QtCore.QRect(10, 300, 130, 25))
        self.button_on_drive.setCheckable(False)
        self.button_on_drive.setObjectName("button_on_drive")
        self.gridFrame = QtWidgets.QFrame(parent=cooling)
        self.gridFrame.setGeometry(QtCore.QRect(10, 10, 410, 280))
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.gridFrame.setLineWidth(2)
        self.gridFrame.setMidLineWidth(0)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_temp_device = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_temp_device.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_temp_device.setObjectName("label_temp_device")
        self.gridLayout.addWidget(self.label_temp_device, 6, 0, 1, 1)
        self.label_flow = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_flow.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_flow.setObjectName("label_flow")
        self.gridLayout.addWidget(self.label_flow, 5, 0, 1, 1)
        self.label_manometer_2 = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_manometer_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_manometer_2.setObjectName("label_manometer_2")
        self.gridLayout.addWidget(self.label_manometer_2, 4, 0, 1, 1)
        self.label_manometer_1_color = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_manometer_1_color.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_manometer_1_color.setObjectName("label_manometer_1_color")
        self.gridLayout.addWidget(self.label_manometer_1_color, 3, 1, 1, 1)
        self.label_manometer_2_color = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_manometer_2_color.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_manometer_2_color.setObjectName("label_manometer_2_color")
        self.gridLayout.addWidget(self.label_manometer_2_color, 4, 1, 1, 1)
        self.label_temp = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_temp.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_temp.setObjectName("label_temp")
        self.gridLayout.addWidget(self.label_temp, 6, 1, 1, 1)
        self.label_speed = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_speed.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout.addWidget(self.label_speed, 5, 1, 1, 1)
        self.label_valve_1_color = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_valve_1_color.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_valve_1_color.setObjectName("label_valve_1_color")
        self.gridLayout.addWidget(self.label_valve_1_color, 1, 1, 1, 1)
        self.label_valve_2_color = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_valve_2_color.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_valve_2_color.setObjectName("label_valve_2_color")
        self.gridLayout.addWidget(self.label_valve_2_color, 2, 1, 1, 1)
        self.label_valve_2 = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_valve_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_valve_2.setObjectName("label_valve_2")
        self.gridLayout.addWidget(self.label_valve_2, 2, 0, 1, 1)
        self.label_valve_1 = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_valve_1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_valve_1.setObjectName("label_valve_1")
        self.gridLayout.addWidget(self.label_valve_1, 1, 0, 1, 1)
        self.label_manometer_1 = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_manometer_1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_manometer_1.setObjectName("label_manometer_1")
        self.gridLayout.addWidget(self.label_manometer_1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridFrame)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.button_on_drive = QtWidgets.QPushButton(parent=cooling)
        self.button_on_drive.setGeometry(QtCore.QRect(10, 300, 130, 25))
        self.button_on_drive.setCheckable(False)
        self.button_on_drive.setObjectName("button_on_drive")

        self.retranslateUi(cooling)
        QtCore.QMetaObject.connectSlotsByName(cooling)

        # ---------------------------------------------------
        self.button_on_drive.clicked.connect(self.on_off_drive)

        # ---------------------------------------------------
        # Запуск обновления информации для температуры
        self.Thread_is = Thread(label_temp=self.label_temp, label_speed=self.label_speed)
        self.Thread_is.start()

    def on_off_drive(self):
        self.result = QMessageBox()

        self.result.setText("Включить или выключить привод ?")
        self.result.setWindowTitle("Монитор")
        self.result.setIcon(QMessageBox.Icon.Question)

        cansel = self.result.addButton('Отмена', self.result.ButtonRole.RejectRole)
        self.result.setDefaultButton(cansel)

        self.on = self.result.addButton('Включить', self.result.ButtonRole.AcceptRole)
        self.off = self.result.addButton('Выключить', self.result.ButtonRole.AcceptRole)

        self.result.buttonClicked.connect(self.answer_on_off_driver)
        self.result.exec()

    def answer_on_off_driver(self, e):
        # todo сделать включение выключения клапана
        if e.text() == "Включить":
            print('Включить')

        elif e.text() == "Выключить":
            print("Выключить")
            self.label_temp.setStyleSheet("background-color:red")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        #cooling.setWindowTitle(_translate("cooling", "Система охлаждения"))
        self.button_on_drive.setText(_translate("cooling", "Включение привода"))
        self.label_temp_device.setText(_translate("cooling", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">Температура в магистрали расходомера"
                                                             "</span></p></body></html>"))
        self.label_flow.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\""
                                                      ">Скорость потока в l/min</span></p></body></html>"))
        self.label_manometer_2.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\""
                                                             ">Манометр 2</span></p></body></html>"))
        self.label_manometer_1_color.setText(_translate("cooling", "Цвет манометра 1"))
        self.label_manometer_2_color.setText(_translate("cooling", "Цвет манометр 2"))
        self.label_temp.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\">"
                                                      "Температура</span></p></body></html>"))
        self.label_speed.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\">"
                                                       "Скорость</span></p></body></html>"))
        self.label_valve_1_color.setText(_translate("cooling","<html><head/><body><p>Цвет клапана 1</p></body></html>"))
        self.label_valve_2_color.setText(_translate("cooling","<html><head/><body><p>Цвет клапана 2</p></body></html>"))
        self.label_valve_2.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\">"
                                                         "Клапан 2</span></p></body></html>"))
        self.label_valve_1.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\">"
                                                         "Клапан 1</span></p></body></html>"))
        self.label_manometer_1.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-weight:600;\">"
                                                             "Манометра 1</span></p></body></html>"))
        self.label.setText(_translate("cooling", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;"
                                                 "\">Состояние системы охлаждения</span></p></body></html>"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    cooling = QtWidgets.QWidget()
    ui = Ui_cooling()
    ui.setupUi(cooling)
    cooling.show()
    sys.exit(app.exec())
